# Generated by Django 3.0.8 on 2020-07-25 00:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registro_app', '0005_auto_20200724_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mesencurso',
            name='obra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registro_app.Obra'),
        ),
        migrations.AlterField(
            model_name='qse',
            name='mes_en_curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registro_app.MesEnCurso'),
        ),
    ]
