# Generated by Django 3.0.8 on 2020-07-25 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro_app', '0006_auto_20200724_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qse',
            name='fecha',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='qse',
            name='nro',
            field=models.IntegerField(blank=True, unique=True),
        ),
    ]
