# Generated by Django 3.0.8 on 2020-07-25 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registro_app', '0007_auto_20200724_2006'),
    ]

    operations = [
        migrations.RenameField(
            model_name='qse',
            old_name='casificacion',
            new_name='clasificacion',
        ),
        migrations.RenameField(
            model_name='qse',
            old_name='Objeto',
            new_name='objeto',
        ),
    ]
