# Generated by Django 3.0.8 on 2020-07-26 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro_app', '0008_auto_20200724_2112'),
    ]

    operations = [
        migrations.AddField(
            model_name='zona',
            name='objetos',
            field=models.ManyToManyField(to='registro_app.Objeto', verbose_name='lista de objetos'),
        ),
    ]
