# Generated by Django 3.0.8 on 2020-07-28 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registro_app', '0010_brigada_integrantes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mesencurso',
            name='mes',
        ),
    ]
