# Generated by Django 3.0.8 on 2020-07-28 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro_app', '0011_remove_mesencurso_mes'),
    ]

    operations = [
        migrations.AddField(
            model_name='mesencurso',
            name='mes',
            field=models.IntegerField(choices=[(1, 'Enero'), (2, 'Febrero')]),
        ),
    ]
