# Generated by Django 3.0.8 on 2020-08-04 02:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registro_app', '0015_auto_20200728_1949'),
    ]

    operations = [
        migrations.AddField(
            model_name='convenio',
            name='obra',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='registro_app.Obra'),
        ),
    ]
