# Generated by Django 3.0.8 on 2020-08-05 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registro_app', '0018_auto_20200804_2249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brigada',
            name='integrantes',
        ),
    ]
